cryptodev-linux: import v1.13
The current version is v.12 and this version does not support kernel 6.6.
The following compilation error is observed:
/home/sahbot/workspace/build/buildsystem/build_dir/target-aarch64-openwrt-linux-musl_musl/linux-mediatek_filogic/cryptodev-linux-cryptodev-linux-1.12/ioctl.c:1187:18: error: 'struct ctl_table' has no member named 'child'
 1187 |                 .child          = verbosity_ctl_dir,
      |                  ^~~~~
/home/sahbot/workspace/build/buildsystem/build_dir/target-aarch64-openwrt-linux-musl_musl/linux-mediatek_filogic/cryptodev-linux-cryptodev-linux-1.12/ioctl.c:1187:35: error: positional initialization of field in 'struct' declared with 'designated_init' attribute [-Werror=designated-init]
 1187 |                 .child          = verbosity_ctl_dir,
      |                                   ^~~~~~~~~~~~~~~~~
/home/sahbot/workspace/build/buildsystem/build_dir/target-aarch64-openwrt-linux-musl_musl/linux-mediatek_filogic/cryptodev-linux-cryptodev-linux-1.12/ioctl.c:1187:35: note: (near initialization for 'verbosity_ctl_root[0]')
/home/sahbot/workspace/build/buildsystem/build_dir/target-aarch64-openwrt-linux-musl_musl/linux-mediatek_filogic/cryptodev-linux-cryptodev-linux-1.12/ioctl.c:1187:35: error: incompatible types when initializing type 'enum <anonymous>' using type 'struct ctl_table *'
/home/sahbot/workspace/build/buildsystem/build_dir/target-aarch64-openwrt-linux-musl_musl/linux-mediatek_filogic/cryptodev-linux-cryptodev-linux-1.12/ioctl.c: In function 'init_cryptodev':
/home/sahbot/workspace/build/buildsystem/build_dir/target-aarch64-openwrt-linux-musl_musl/linux-mediatek_filogic/cryptodev-linux-cryptodev-linux-1.12/ioctl.c:1208:35: error: implicit declaration of function 'register_sysctl_table'; did you mean 'unregister_sysctl_table'? [-Werror=implicit-function-declaration]
 1208 |         verbosity_sysctl_header = register_sysctl_table(verbosity_ctl_root);
      |                                   ^~~~~~~~~~~~~~~~~~~~~
      |                                   unregister_sysctl_table
/home/sahbot/workspace/build/buildsystem/build_dir/target-aarch64-openwrt-linux-musl_musl/linux-mediatek_filogic/cryptodev-linux-cryptodev-linux-1.12/ioctl.c:1208:33: error: assignment to 'struct ctl_table_header *' from 'int' makes pointer from integer without a cast [-Werror=int-conversion]
 1208 |         verbosity_sysctl_header = register_sysctl_table(verbosity_ctl_root);
      |                                 ^
cc1: all warnings being treated as errors

So let's update to v1.13 where this compatibility issue is fixed.

This package import is taken from openwrt master branch at d40d64fc62f51a83b48a6c21b68d8a00e83c72c3

Issue: HOP-11341
GitOrigin-RevId: 476929382c263cd06ba07c9b0bb37fce0ba0036b