[util-linux] do not disable linking with libutil
In https://github.com/openwrt/openwrt/commit/28cec438071c6a5ce90ed4606df7cbe6ad8a100c the util-linux package is build using meson iso autoconf.
Previously in autoconf:
-without-util was not set

For some reason they have set in the meson build:
-Dlibutil=disabled

When compiling with glibc, we get the following warning:

/opt/toolchains/toolchain-arm-cortex-a7-gcc-8.4.0-glibc-eabi/bin/../lib/gcc/arm-openwrt-linux-gnueabi/8.4.0/../../../../arm-openwrt-linux-gnueabi/bin/ld: script.p/lib_pty-session.c.o: in function `ul_pty_setup':
pty-session.c:(.text+0x1570): undefined reference to `openpty'
/opt/toolchains/toolchain-arm-cortex-a7-gcc-8.4.0-glibc-eabi/bin/../lib/gcc/arm-openwrt-linux-gnueabi/8.4.0/../../../../arm-openwrt-linux-gnueabi/bin/ld: pty-session.c:(.text+0x1698): undefined reference to `openpty'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
make[3]: *** [Makefile:908: /home/sahbot/workspace/build/buildsystem/build_dir/target-arm-openwrt-linux-gnueabi_glibc/util-linux-2.39/.built] Error 1
make[3]: Leaving directory '/home/sahbot/workspace/build/buildsystem/package/utils/util-linux'
time: package/utils/util-linux/compile#56.13#28.28#87.18
    ERROR: package/utils/util-linux failed to build.

Even when linking with libutil is disabled in meson, the util-linux package compiles some c files which need the openpty function (they include pty.h). In autoconf it looks like there are some checks when disabling linking with libutil. In this case, the extra c files are not compiled and all functionality linked to "libutil" is skipped.
We do not see this issue on a musl (default openwrt) build, since openpty is included in the libc.so.

It probably does not harm to remove -Dlibutil=disabled in the meson build. Meson will then figure out libutil is availble and will link with it properly.

GitOrigin-RevId: c38ffa3f494b8c43a492147b229891f1ee79e492