e2fsprogs: link with library libcom_err
When compiling a package that depends on libext2fs, a linker error is
thrown:

    libext2fs.so: undefined reference to_et_list'
    libext2fs.so: undefined reference to com_err'

The OpenWrt package makefile for e2fsprogs overwrites the additional
libraries that have to be linked in libext2fs by re-defining the
ELF_OTHER_LIBS variable. Libcom_err was missed here.

Issue: CSSP-4683 - [CHR2fB][SWUpdate]link error with libext2fs
GitOrigin-RevId: cd44bf2783e45dba7a5fc3f704b0ed5dbc448883