gpio-button-hotplug: only use devm_fwnode_gpiod_get on newer kernels
The following compilation error is observed with 5.4 kernel:
gpio-button-hotplug.c:541:19: error: implicit declaration of function 'devm_fwnode_gpiod_get'; did you mean 'devm_gpiod_get'? [-Werror=implicit-function-declaration]
    bdata->gpiod = devm_fwnode_gpiod_get(dev,
                   ^~~~~~~~~~~~~~~~~~~~~
                   devm_gpiod_get
/home/sahbot/workspace/build/buildsystem/build_dir/target-aarch64-openwrt-linux-musl_musl/linux-mediatek_mt7986/gpio-button-hotplug/gpio-button-hotplug.c:541:17: warning: assignment to 'struct gpio_desc *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
    bdata->gpiod = devm_fwnode_gpiod_get(dev,
                 ^
cc1: some warnings being treated as errors

It turns out devm_fwnode_gpiod_get is only introduced in linux 5.10 (and reworked in later versions)

To be backwards compatible, let us only use the function in kernels starting from 6.0 and restore the old behavior for older kernels.

Issue: HOP-11341
GitOrigin-RevId: acdf4e3534b7677336f2292f3d976624aad01f82