botan: set compiler to gcc
Since we use ccache, it looks like the compiler cannot be determined automatically:
ERROR: Could not figure out what compiler type '/home/sahbot/workspace/build/buildsystem/staging_dir/toolchain-aarch64-openwrt-linux-musl/bin/ccache_cxx' is, use --cc to set

Therefore, let's directly set the compiler type to gcc.

GitOrigin-RevId: 8fdf683794fb21ee44b20dd2fda3efc106e75edc