strace: import v6.6
Taken from openwrt master branch at commit f6309956778adbe541db220a12662e61c1f8765e
This fixes compilation with kernels >= 6.6

In file included from btrfs.c:51:
xlat/btrfs_key_types.h:167:37: error: 'BTRFS_EXTENT_REF_V0_KEY' undeclared here (not in a function); did you mean 'BTRFS_EXTENT_DATA_KEY'?
  167 | static_assert((unsigned long long) (BTRFS_EXTENT_REF_V0_KEY)
      |                                     ^~~~~~~~~~~~~~~~~~~~~~~
      |                                     BTRFS_EXTENT_DATA_KEY
xlat/btrfs_key_types.h:167:15: error: expression in static assertion is not an integer
  167 | static_assert((unsigned long long) (BTRFS_EXTENT_REF_V0_KEY)
      |               ^
xlat/btrfs_key_types.h:175:15: error: expression in static assertion is not an integer
  175 | static_assert((unsigned long long) (BTRFS_SHARED_BLOCK_REF_KEY)
      |               ^
make[6]: *** [Makefile:4687: libstrace_a-btrfs.o] Error 1

Issue: HOP-11341
GitOrigin-RevId: 09d5aebea3b4f89e39c7232f94286a3fa67c96a0