ubus: import v2025-05-16
We need a newer version of ubus to be able to compile udebug.
Currently following compilation issue is seen:
lib.c: In function 'udebug_ubus_init':
lib.c:180:17: error: 'struct ubus_subscriber' has no member named 'new_obj_cb'
  180 |         ctx->sub.new_obj_cb = udebug_ubus_new_obj_cb;
      |                 ^
ninja: build stopped: subcommand failed.

Imported from openwrt master branch at 707a89bc264e0a2b6593da753301912d7ec40f77

(cherry picked from commit 6ca1d91d282a20e666d4a72e43bd2281b84238b9)

Issue: HOP-11341
GitOrigin-RevId: 05172f59d17415632ea5ad6f3428f46d3d7b2695