libubox: import v2024-03-29
udebug depends on libubox. Currently the following compilation error is seen when trying to compile udebug:
error: libubox/udebug.h: No such file or directory
    1 | #include <libubox/udebug.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.

So let's bump libubox to a newer version to fix this problem.

Taken from openwrt master branch at b906a9c78ef51cdc2f97dc6c39f92b9295f48d4e

Issue: HOP-11341
GitOrigin-RevId: 2751cb1f8e9d33d900d7e5cbc3f36de4879c7f5f