iwinfo: import v2024-10-20
This newer version of iwinfo is needed to compile the newer version of rpcd.
Current compilation error without this upstep:
iwinfo.c: In function 'rpc_iwinfo_call_hw_ht_mode':
iwinfo.c:287:26: error: implicit declaration of function 'iwinfo_htmode_is_eht'; did you mean 'iwinfo_htmode_is_vht'? [-Werror=implicit-function-declaration]
  287 |                 else if (iwinfo_htmode_is_eht(htmode))
      |                          ^~~~~~~~~~~~~~~~~~~~
      |                          iwinfo_htmode_is_vht
iwinfo.c: In function 'rpc_iwinfo_add_rateinfo':
iwinfo.c:461:40: error: 'struct iwinfo_rate_entry' has no member named 'is_eht'; did you mean 'is_ht'?
  461 |         blobmsg_add_u8(&buf, "eht", r->is_eht);
      |                                        ^~~~~~
      |                                        is_ht
iwinfo.c:462:39: error: 'struct iwinfo_rate_entry' has no member named 'mhz_hi'
  462 |         blobmsg_add_u32(&buf, "mhz", r->mhz_hi * 256 + r->mhz);
      |                                       ^~
iwinfo.c:481:21: error: 'struct iwinfo_rate_entry' has no member named 'is_eht'; did you mean 'is_ht'?
  481 |         else if (r->is_eht) {
      |                     ^~~~~~
      |                     is_ht
iwinfo.c:484:52: error: 'struct iwinfo_rate_entry' has no member named 'eht_gi'; did you mean 'he_gi'?
  484 |                 blobmsg_add_u32(&buf, "eht_gi", r->eht_gi);
      |                                                    ^~~~~~
      |                                                    he_gi
cc1: all warnings being treated as errors

Imported from openwrt master branch at commit cb60bee04db6cdfe5062c20b816244ab49f2e9d1

Issue: HOP-11341
GitOrigin-RevId: 184c3c17eab6b8c5ab0d5d68844c8204fa8f48e2