ppp-prpl: prevent pppoa from compiling
We removed ppp-mod-pppoa from our ppp-prpl package because we do not need it.
It turns out however that ppp atm package is still being build (just not installed).

On an external kernel we see the following error:
In file included from ./linux/atm.h:20,
		 from ./atm.h:11,
		 from pppoatm.c:23:
./linux/compiler.h:275:10: fatal error: asm/rwonce.h: No such file or directory
| #include <asm/rwonce.h> | ^~~~~~~~~~~~~~ compilation terminated.

The package tries to use internal kernel headers, what should not be done.
On openwrt native kernels this still works (probably the headers are somehow exported to uapi).
On proprietary kernels build without openwrt this seems to fail (for good reasons).

Since we don't need pppoa, let's also not compile it.

Issue: CSSP-5807
GitOrigin-RevId: dd1da52ae648f169f7b725478d527683b15a923a